### ISSUE TITLE
No sound when running Stargate in MEGA65

### ISSUE THREAD

**Issue by tonedef71** [sho3string/StargateMEGA65_R3_R6#1]
The sound file in the Mame distribution (`sg.snd`) is 2048 bytes
![image](https://github.com/user-attachments/assets/2cd67d8d-42d5-418d-9e62-e106e2192071)

but the one needed by the core (`sound.snd`) appears to be 4096 bytes:
![image](https://github.com/user-attachments/assets/0627e22a-3ae3-49de-88ff-0d9f773935c0)

Should the installer script be patching the bytes of the `sg.snd` file to make it the necessary size for the required `sound.snd` file?

**Comment by sho3string** [comment]
It might need padding, I'll look into it.

Thanks for the report.

**Comment by tonedef71** [comment]
I have confirmed that the `.ps1` and `.sh` installer script files have been patched appropriately.

Closing this issue as `fixed`.
